// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: iktato.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Iktato {
  public static partial class IktatoService
  {
    static readonly string __ServiceName = "Iktato.IktatoService";

    static readonly grpc::Marshaller<global::Iktato.LoginMessage> __Marshaller_Iktato_LoginMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Iktato.LoginMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Iktato.User> __Marshaller_Iktato_User = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Iktato.User.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Iktato.AuthToken> __Marshaller_Iktato_AuthToken = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Iktato.AuthToken.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Iktato.Answer> __Marshaller_Iktato_Answer = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Iktato.Answer.Parser.ParseFrom);

    static readonly grpc::Method<global::Iktato.LoginMessage, global::Iktato.User> __Method_Login = new grpc::Method<global::Iktato.LoginMessage, global::Iktato.User>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Login",
        __Marshaller_Iktato_LoginMessage,
        __Marshaller_Iktato_User);

    static readonly grpc::Method<global::Iktato.AuthToken, global::Iktato.Answer> __Method_Logout = new grpc::Method<global::Iktato.AuthToken, global::Iktato.Answer>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Logout",
        __Marshaller_Iktato_AuthToken,
        __Marshaller_Iktato_Answer);

    static readonly grpc::Method<global::Iktato.AuthToken, global::Iktato.Answer> __Method_Register = new grpc::Method<global::Iktato.AuthToken, global::Iktato.Answer>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Register",
        __Marshaller_Iktato_AuthToken,
        __Marshaller_Iktato_Answer);

    static readonly grpc::Method<global::Iktato.AuthToken, global::Iktato.Answer> __Method_ModifyUser = new grpc::Method<global::Iktato.AuthToken, global::Iktato.Answer>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ModifyUser",
        __Marshaller_Iktato_AuthToken,
        __Marshaller_Iktato_Answer);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Iktato.IktatoReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of IktatoService</summary>
    [grpc::BindServiceMethod(typeof(IktatoService), "BindService")]
    public abstract partial class IktatoServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Iktato.User> Login(global::Iktato.LoginMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Iktato.Answer> Logout(global::Iktato.AuthToken request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Iktato.Answer> Register(global::Iktato.AuthToken request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Iktato.Answer> ModifyUser(global::Iktato.AuthToken request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for IktatoService</summary>
    public partial class IktatoServiceClient : grpc::ClientBase<IktatoServiceClient>
    {
      /// <summary>Creates a new client for IktatoService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public IktatoServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for IktatoService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public IktatoServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected IktatoServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected IktatoServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Iktato.User Login(global::Iktato.LoginMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Login(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Iktato.User Login(global::Iktato.LoginMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Login, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Iktato.User> LoginAsync(global::Iktato.LoginMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Iktato.User> LoginAsync(global::Iktato.LoginMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Login, null, options, request);
      }
      public virtual global::Iktato.Answer Logout(global::Iktato.AuthToken request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Logout(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Iktato.Answer Logout(global::Iktato.AuthToken request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Logout, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Iktato.Answer> LogoutAsync(global::Iktato.AuthToken request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LogoutAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Iktato.Answer> LogoutAsync(global::Iktato.AuthToken request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Logout, null, options, request);
      }
      public virtual global::Iktato.Answer Register(global::Iktato.AuthToken request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Register(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Iktato.Answer Register(global::Iktato.AuthToken request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Register, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Iktato.Answer> RegisterAsync(global::Iktato.AuthToken request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegisterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Iktato.Answer> RegisterAsync(global::Iktato.AuthToken request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Register, null, options, request);
      }
      public virtual global::Iktato.Answer ModifyUser(global::Iktato.AuthToken request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ModifyUser(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Iktato.Answer ModifyUser(global::Iktato.AuthToken request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ModifyUser, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Iktato.Answer> ModifyUserAsync(global::Iktato.AuthToken request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ModifyUserAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Iktato.Answer> ModifyUserAsync(global::Iktato.AuthToken request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ModifyUser, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override IktatoServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new IktatoServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(IktatoServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Login, serviceImpl.Login)
          .AddMethod(__Method_Logout, serviceImpl.Logout)
          .AddMethod(__Method_Register, serviceImpl.Register)
          .AddMethod(__Method_ModifyUser, serviceImpl.ModifyUser).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, IktatoServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Login, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Iktato.LoginMessage, global::Iktato.User>(serviceImpl.Login));
      serviceBinder.AddMethod(__Method_Logout, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Iktato.AuthToken, global::Iktato.Answer>(serviceImpl.Logout));
      serviceBinder.AddMethod(__Method_Register, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Iktato.AuthToken, global::Iktato.Answer>(serviceImpl.Register));
      serviceBinder.AddMethod(__Method_ModifyUser, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Iktato.AuthToken, global::Iktato.Answer>(serviceImpl.ModifyUser));
    }

  }
}
#endregion
