call getikonyvek(2);
call getjellegek(2);
call getpartners(2);
insert into partner(name,telephely,created_by)value("E-on",1,1);
select * from partner;
call getprivileges();
call getshortikonyv(2);
call gettelephelyek(1);
select * from felh_telephely;
call getugyintezok(1);
select * from telephely;
call getusers();
call addgroup("Ellátotti","E",2,1, @v);
SELECT @v;
select * from csoport;
call addkind("E-mail",1,1, @v);
select @v;
select * from jelleg;
call addpartner(1,2,"EKE",@v);
select @v;
select * from partner;
delete from partner where id = 3;
select * from user;
select * from felh_telephely;