truncate ikonyv;
truncate partnerugyintezokapcsolo;
truncate partner;
truncate partnerugyintezo;
truncate ugyintezo;
truncate jelleg;
truncate csoport;
truncate felh_telephely;
truncate user;
truncate privilege;
truncate evek;
insert into privilege(privilege)value("admin");
insert into privilege(privilege)value("user");
call addtelephely("Vajda");
call addtelephely("Rákóczi");
call addtelephely("Tessedik");
call addUser('misi','kiscica','Pekár Mihály',1);
call addUserToTelephely(1,1);
call addUserToTelephely(1,2);
call addUserToTelephely(1,3);
call addGroup("Konyha","K",1,1);
call addGroup("Munkaügy","M",1,1);
call addKind("E-mail",1,1);
call addKind("Fax",1,1);
call addKind("Levél",1,1);
insert into evek(year,active,created_by)value(2018,0,1);
insert into evek(year,active,created_by)value(2019,1,1);
call addUgyintezo("Brachna Anita",1,1);
insert into partner(name,created_by,telephely)value("Kiscica",1,2);
insert into partnerugyintezo(name)value("Kis Cica");
insert into partnerugyintezokapcsolo(partnerid,partnerugyintezoid,telephely)value(1,1,2);
CALL addRootIkonyv("Próba tárgy","11111-111-1",1,1,1,2,2,3,0,STR_TO_DATE('2019.12.20','%Y.%m.%d'),STR_TO_DATE('2019.12.22','%Y.%m.%d'),"Ez egy szöveg a próba iktatáshoz ami bármilyen hosszu lehet akár lorem ipsumot is beilleszthetnék ide, de vajon van értelme?", @v); 

call getIkonyvek(1);
