SET FOREIGN_KEY_CHECKS=0;
truncate ikonyv;
truncate ikonyvpartnerei;
truncate partner;
truncate partnerugyintezo;
truncate ugyintezo;
truncate jelleg;
truncate csoport;
truncate felh_telephely;
truncate user;
truncate privilege;
truncate evek;
truncate user;
truncate telephely;
insert into privilege(privilege)value("admin");
insert into privilege(privilege)value("user");
call addUser('admin','kiscica','Administrator',1,@v);
call addtelephely("Vajda",1, @v);
call addtelephely("Rákóczi",1, @v);
call addtelephely("Tessedik",1, @v);
call addUser('misi','kiscica','Pekár Mihály',2,@v);
select * from felh_telephely;
select * from user;
call addUserToTelephely(1,1);
call addUserToTelephely(1,2);
call addUserToTelephely(1,3);
call addUserToTelephely(2,1);
call addUserToTelephely(2,2);
call addUserToTelephely(3,1);
call addUserToTelephely(3,2);
call addUserToTelephely(3,3);
call addGroup("Konyha","K",1,2, @v);
call addGroup("Munkaügy","M",1,2, @v);
call addgroup("kiscica","c",2,2, @v);
call addKind("E-mail",1,2, @v);
call addKind("Fax",1,2, @v);
call addKind("Levél",1,2, @v);
call addKind("E-mail",2,2, @v);
call addKind("Fax",2,2, @v);
call addKind("Levél",2,2, @v);
call addyear(2019,2,@v);
call addyear(2020,2,@v);
update evek set  active = 1 where id = 2;
call addUgyintezo("Brachna Anita",2,2,@v);
call addpartner(2,1,"EKE",@v);
call addpartner(2,2,"E-ON",@v);
call addpartnerugyintezo("Balla Tamás",2,1,@v);
call addpartnerugyintezo("Kis János",2,2,@v);
CALL addRootIkonyv("Próba tárgy","11111-111-1",1,1,1,1,2,2,3,0,STR_TO_DATE('2019.12.20','%Y.%m.%d'),STR_TO_DATE('2019.12.22','%Y.%m.%d'),"Ez egy szöveg a próba iktatáshoz ami bármilyen hosszu lehet akár lorem ipsumot is beilleszthetnék ide, de vajon van értelme?", @v,@b); 
call getIkonyvek(1);
select * from partner;
SET FOREIGN_KEY_CHECKS=1;
select * from telephely;
select * from user;
select * from felh_telephely;
call gettelephelyek(2);
select * from evek;
delete from evek where id = 3;
update evek set active = 1 where id= 2;
select * from ikonyv;

CALL addsubIkonyv("Próba tárgy","11111-111-1",1,1,1,1,2,2,3,0,STR_TO_DATE('2019.12.20','%Y.%m.%d'),STR_TO_DATE('2019.12.22','%Y.%m.%d'),"Ez egy szöveg a próba iktatáshoz ami bármilyen hosszu lehet akár lorem ipsumot is beilleszthetnék ide, de vajon van értelme?",1, @v,@b); 
select CONCAT(SUBSTRING_INDEX("B-SZ/R/3/2020",'/',3),"-",1,"/",2020);   
select * from ikonyv;
select * from ikonyvpartnerei;
